plugins {
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.139' apply false
}

group = mod_group_id
version = mod_version

allprojects {
    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = "ftbMavenReleases"
            url = "https://maven.ftb.dev/releases"
        }
        maven {
            url = "https://maven.architectury.dev/"
        }
    }
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
