org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=callyou
mod_name=CallYouByYourName
mod_license=GPL-3.0 LICENSE
mod_version=2001.2.0-build.1
mod_group_id=cn.qihuang02.callyou
mod_authors=QiHuang02
mod_description=Chat mention enhancement for Forge 1.20.1.\nHighlights @player with reply buttons, supports @item sharing and @spot coordinates.\nAdds @here/@near/@team pings plus an in-game prefs GUI for muting or blocking mentions.
