org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.218
loader_version_range=[1,)

ftb_teams_version = 2101.1.9
ftb_chunks_version = 2101.1.13
ftb_library_version = 2101.1.30
architectury_version = 13.0.8

ldlib2_version=2.1.7

## Mod Properties
mod_id=callyou
mod_name=CallYouByYourName
mod_license=GPL-3.0 LICENSE
mod_version=2101.2.0-build.36
mod_group_id=cn.qihuang02.callyou
mod_authors=QiHuang02
mod_description=Chat mention enhancement for NeoForge 1.21.1.\nHighlights @player with reply buttons, supports @item sharing and @spot coordinates.\nAdds @here/@near/@team pings plus an in-game prefs GUI for muting or blocking mentions.
